development:
  adapter: postgresql
  encoding: unicode
  database: minesweeper_development
  pool: 5
  username: Rob
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: minesweeper_test
  pool: 5
  username: Rob
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: minesweeper_production
  pool: 5
  username: Rob
  password:
